<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 ./static/girl_5.glb --transform
Author: Blue Spirit (https://sketchfab.com/Blue-Spirit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/swamp-witch-personal-design-1c5cf4ff54b84eea86dc1c426dee7116
Title: Swamp Witch (Personal Design)
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/girl_5-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group rotation={[-Math.PI / 2, 0, 0]}>
        <T is={gltf.nodes._rootJoint} />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_7.geometry}
          material={gltf.materials.Skin}
          skeleton={gltf.nodes.Object_7.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_8.geometry}
          material={gltf.materials.Mouth}
          skeleton={gltf.nodes.Object_8.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_9.geometry}
          material={gltf.materials.Eyes}
          skeleton={gltf.nodes.Object_9.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_11.geometry}
          material={gltf.materials.Skin}
          skeleton={gltf.nodes.Object_11.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_12.geometry}
          material={gltf.materials.Head}
          skeleton={gltf.nodes.Object_12.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_14.geometry}
          material={gltf.materials.Bandages_and_Chains}
          skeleton={gltf.nodes.Object_14.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_16.geometry}
          material={gltf.materials.Bandages_and_Chains}
          skeleton={gltf.nodes.Object_16.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_18.geometry}
          material={gltf.materials.Bandages_and_Chains}
          skeleton={gltf.nodes.Object_18.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_20.geometry}
          material={gltf.materials.Bandages_and_Chains}
          skeleton={gltf.nodes.Object_20.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_22.geometry}
          material={gltf.materials.Bandages_and_Chains}
          skeleton={gltf.nodes.Object_22.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_24.geometry}
          material={gltf.materials.Bandages_and_Chains}
          skeleton={gltf.nodes.Object_24.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_26.geometry}
          material={gltf.materials.Hood}
          skeleton={gltf.nodes.Object_26.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_28.geometry}
          material={gltf.materials.Cloths}
          skeleton={gltf.nodes.Object_28.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_30.geometry}
          material={gltf.materials.Cloths}
          skeleton={gltf.nodes.Object_30.skeleton}
        />
        <T.SkinnedMesh
          geometry={gltf.nodes.Object_32.geometry}
          material={gltf.materials.Cloths}
          skeleton={gltf.nodes.Object_32.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
