<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./static/mahiro.glb
Author: ScarletJadeDream (https://sketchfab.com/ScarletJadeDream)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/mahiro-oyama-onii-chan-wa-oshimai-f97ecef2a58b4846a5303a7208bcc873
Title: Mahiro Oyama - Onii-chan wa Oshimai!
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/staticmahiro.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="abd016b8024042979a282043fedb7708fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="Torso_Eye_L" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Map_Platform" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <T.Mesh
                  name="Map_Platform_Map_0"
                  geometry={gltf.nodes.Map_Platform_Map_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group name="Map_Wall" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <T.Mesh
                  name="Map_Wall_Map_0"
                  geometry={gltf.nodes.Map_Wall_Map_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group name="Map_Blackboard01" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <T.Mesh
                  name="Map_Blackboard01_Map_0"
                  geometry={gltf.nodes.Map_Blackboard01_Map_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group name="Map_Blackboard02" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <T.Mesh
                  name="Map_Blackboard02_Map_0"
                  geometry={gltf.nodes.Map_Blackboard02_Map_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group name="char_grp" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <T.Group name="rig">
                  <T.Group name="Object_15">
                    <T is={gltf.nodes._rootJoint} />
                    <T.Group name="Object_17" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_835" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_838" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_841" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_843" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_845" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_848" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_851" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_854" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_857" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_860" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_863" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_866" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_869" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_872" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_875" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_878" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_881" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_884" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_887" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_890" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_893" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_896" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_899" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_902" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_905" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_908" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_911" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_914" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_917" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_920" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_923" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_926" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_929" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_932" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_935" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_938" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_941" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_944" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_947" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_950" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_953" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_956" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_959" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_962" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_965" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_968" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_971" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_974" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_977" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_980" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_983" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_986" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_989" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_992" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_995" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_998" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1005" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1009" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1013" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1017" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1021" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1024" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1027" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1030" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1033" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1036" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1040" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1043" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1046" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1050" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.Group name="Object_1054" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <T.SkinnedMesh
                      name="Object_18"
                      geometry={gltf.nodes.Object_18.geometry}
                      material={gltf.materials.material_1}
                      skeleton={gltf.nodes.Object_18.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_836"
                      geometry={gltf.nodes.Object_836.geometry}
                      material={gltf.materials.Body}
                      skeleton={gltf.nodes.Object_836.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_837"
                      geometry={gltf.nodes.Object_837.geometry}
                      material={gltf.materials.Body_OutLine}
                      skeleton={gltf.nodes.Object_837.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_839"
                      geometry={gltf.nodes.Object_839.geometry}
                      material={gltf.materials.Body}
                      skeleton={gltf.nodes.Object_839.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_840"
                      geometry={gltf.nodes.Object_840.geometry}
                      material={gltf.materials.Body_OutLine}
                      skeleton={gltf.nodes.Object_840.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_842"
                      geometry={gltf.nodes.Object_842.geometry}
                      material={gltf.materials.material_1}
                      skeleton={gltf.nodes.Object_842.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_844"
                      geometry={gltf.nodes.Object_844.geometry}
                      material={gltf.materials.material_1}
                      skeleton={gltf.nodes.Object_844.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_846"
                      geometry={gltf.nodes.Object_846.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_846.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_847"
                      geometry={gltf.nodes.Object_847.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_847.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_849"
                      geometry={gltf.nodes.Object_849.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_849.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_850"
                      geometry={gltf.nodes.Object_850.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_850.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_852"
                      geometry={gltf.nodes.Object_852.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_852.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_853"
                      geometry={gltf.nodes.Object_853.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_853.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_855"
                      geometry={gltf.nodes.Object_855.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_855.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_856"
                      geometry={gltf.nodes.Object_856.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_856.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_858"
                      geometry={gltf.nodes.Object_858.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_858.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_859"
                      geometry={gltf.nodes.Object_859.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_859.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_861"
                      geometry={gltf.nodes.Object_861.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_861.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_862"
                      geometry={gltf.nodes.Object_862.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_862.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_864"
                      geometry={gltf.nodes.Object_864.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_864.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_865"
                      geometry={gltf.nodes.Object_865.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_865.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_867"
                      geometry={gltf.nodes.Object_867.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_867.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_868"
                      geometry={gltf.nodes.Object_868.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_868.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_870"
                      geometry={gltf.nodes.Object_870.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_870.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_871"
                      geometry={gltf.nodes.Object_871.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_871.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_873"
                      geometry={gltf.nodes.Object_873.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_873.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_874"
                      geometry={gltf.nodes.Object_874.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_874.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_876"
                      geometry={gltf.nodes.Object_876.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_876.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_877"
                      geometry={gltf.nodes.Object_877.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_877.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_879"
                      geometry={gltf.nodes.Object_879.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_879.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_880"
                      geometry={gltf.nodes.Object_880.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_880.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_882"
                      geometry={gltf.nodes.Object_882.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_882.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_883"
                      geometry={gltf.nodes.Object_883.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_883.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_885"
                      geometry={gltf.nodes.Object_885.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_885.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_886"
                      geometry={gltf.nodes.Object_886.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_886.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_888"
                      geometry={gltf.nodes.Object_888.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_888.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_889"
                      geometry={gltf.nodes.Object_889.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_889.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_891"
                      geometry={gltf.nodes.Object_891.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_891.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_892"
                      geometry={gltf.nodes.Object_892.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_892.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_894"
                      geometry={gltf.nodes.Object_894.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_894.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_895"
                      geometry={gltf.nodes.Object_895.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_895.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_897"
                      geometry={gltf.nodes.Object_897.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_897.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_898"
                      geometry={gltf.nodes.Object_898.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_898.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_900"
                      geometry={gltf.nodes.Object_900.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_900.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_901"
                      geometry={gltf.nodes.Object_901.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_901.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_903"
                      geometry={gltf.nodes.Object_903.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_903.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_904"
                      geometry={gltf.nodes.Object_904.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_904.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_906"
                      geometry={gltf.nodes.Object_906.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_906.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_907"
                      geometry={gltf.nodes.Object_907.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_907.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_909"
                      geometry={gltf.nodes.Object_909.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_909.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_910"
                      geometry={gltf.nodes.Object_910.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_910.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_912"
                      geometry={gltf.nodes.Object_912.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_912.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_913"
                      geometry={gltf.nodes.Object_913.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_913.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_915"
                      geometry={gltf.nodes.Object_915.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_915.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_916"
                      geometry={gltf.nodes.Object_916.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_916.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_918"
                      geometry={gltf.nodes.Object_918.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_918.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_919"
                      geometry={gltf.nodes.Object_919.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_919.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_921"
                      geometry={gltf.nodes.Object_921.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_921.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_922"
                      geometry={gltf.nodes.Object_922.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_922.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_924"
                      geometry={gltf.nodes.Object_924.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_924.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_925"
                      geometry={gltf.nodes.Object_925.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_925.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_927"
                      geometry={gltf.nodes.Object_927.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_927.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_928"
                      geometry={gltf.nodes.Object_928.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_928.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_930"
                      geometry={gltf.nodes.Object_930.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_930.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_931"
                      geometry={gltf.nodes.Object_931.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_931.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_933"
                      geometry={gltf.nodes.Object_933.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_933.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_934"
                      geometry={gltf.nodes.Object_934.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_934.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_936"
                      geometry={gltf.nodes.Object_936.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_936.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_937"
                      geometry={gltf.nodes.Object_937.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_937.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_939"
                      geometry={gltf.nodes.Object_939.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_939.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_940"
                      geometry={gltf.nodes.Object_940.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_940.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_942"
                      geometry={gltf.nodes.Object_942.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_942.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_943"
                      geometry={gltf.nodes.Object_943.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_943.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_945"
                      geometry={gltf.nodes.Object_945.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_945.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_946"
                      geometry={gltf.nodes.Object_946.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_946.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_948"
                      geometry={gltf.nodes.Object_948.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_948.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_949"
                      geometry={gltf.nodes.Object_949.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_949.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_951"
                      geometry={gltf.nodes.Object_951.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_951.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_952"
                      geometry={gltf.nodes.Object_952.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_952.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_954"
                      geometry={gltf.nodes.Object_954.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_954.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_955"
                      geometry={gltf.nodes.Object_955.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_955.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_957"
                      geometry={gltf.nodes.Object_957.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_957.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_958"
                      geometry={gltf.nodes.Object_958.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_958.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_960"
                      geometry={gltf.nodes.Object_960.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_960.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_961"
                      geometry={gltf.nodes.Object_961.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_961.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_963"
                      geometry={gltf.nodes.Object_963.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_963.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_964"
                      geometry={gltf.nodes.Object_964.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_964.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_966"
                      geometry={gltf.nodes.Object_966.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_966.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_967"
                      geometry={gltf.nodes.Object_967.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_967.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_969"
                      geometry={gltf.nodes.Object_969.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_969.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_970"
                      geometry={gltf.nodes.Object_970.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_970.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_972"
                      geometry={gltf.nodes.Object_972.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_972.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_973"
                      geometry={gltf.nodes.Object_973.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_973.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_975"
                      geometry={gltf.nodes.Object_975.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_975.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_976"
                      geometry={gltf.nodes.Object_976.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_976.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_978"
                      geometry={gltf.nodes.Object_978.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_978.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_979"
                      geometry={gltf.nodes.Object_979.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_979.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_981"
                      geometry={gltf.nodes.Object_981.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_981.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_982"
                      geometry={gltf.nodes.Object_982.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_982.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_984"
                      geometry={gltf.nodes.Object_984.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_984.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_985"
                      geometry={gltf.nodes.Object_985.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_985.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_987"
                      geometry={gltf.nodes.Object_987.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_987.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_988"
                      geometry={gltf.nodes.Object_988.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_988.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_990"
                      geometry={gltf.nodes.Object_990.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_990.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_991"
                      geometry={gltf.nodes.Object_991.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_991.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_993"
                      geometry={gltf.nodes.Object_993.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_993.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_994"
                      geometry={gltf.nodes.Object_994.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_994.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_996"
                      geometry={gltf.nodes.Object_996.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_996.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_997"
                      geometry={gltf.nodes.Object_997.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_997.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_999"
                      geometry={gltf.nodes.Object_999.geometry}
                      material={gltf.materials.Hair}
                      skeleton={gltf.nodes.Object_999.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1000"
                      geometry={gltf.nodes.Object_1000.geometry}
                      material={gltf.materials.Hair_OutLine}
                      skeleton={gltf.nodes.Object_1000.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1002"
                      geometry={gltf.nodes.Object_1002.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1002.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1003"
                      geometry={gltf.nodes.Object_1003.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1003.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1004"
                      geometry={gltf.nodes.Object_1004.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1004.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1006"
                      geometry={gltf.nodes.Object_1006.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1006.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1007"
                      geometry={gltf.nodes.Object_1007.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1007.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1008"
                      geometry={gltf.nodes.Object_1008.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1008.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1010"
                      geometry={gltf.nodes.Object_1010.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1010.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1011"
                      geometry={gltf.nodes.Object_1011.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1011.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1012"
                      geometry={gltf.nodes.Object_1012.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1012.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1014"
                      geometry={gltf.nodes.Object_1014.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1014.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1015"
                      geometry={gltf.nodes.Object_1015.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1015.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1016"
                      geometry={gltf.nodes.Object_1016.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1016.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1018"
                      geometry={gltf.nodes.Object_1018.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1018.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1019"
                      geometry={gltf.nodes.Object_1019.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1019.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1020"
                      geometry={gltf.nodes.Object_1020.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1020.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1022"
                      geometry={gltf.nodes.Object_1022.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1022.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1023"
                      geometry={gltf.nodes.Object_1023.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1023.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1025"
                      geometry={gltf.nodes.Object_1025.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1025.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1026"
                      geometry={gltf.nodes.Object_1026.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1026.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1028"
                      geometry={gltf.nodes.Object_1028.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1028.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1029"
                      geometry={gltf.nodes.Object_1029.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1029.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1031"
                      geometry={gltf.nodes.Object_1031.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1031.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1032"
                      geometry={gltf.nodes.Object_1032.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1032.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1034"
                      geometry={gltf.nodes.Object_1034.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1034.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1035"
                      geometry={gltf.nodes.Object_1035.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1035.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1037"
                      geometry={gltf.nodes.Object_1037.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1037.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1038"
                      geometry={gltf.nodes.Object_1038.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1038.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1039"
                      geometry={gltf.nodes.Object_1039.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1039.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1041"
                      geometry={gltf.nodes.Object_1041.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1041.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1042"
                      geometry={gltf.nodes.Object_1042.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1042.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1044"
                      geometry={gltf.nodes.Object_1044.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1044.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1045"
                      geometry={gltf.nodes.Object_1045.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1045.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1047"
                      geometry={gltf.nodes.Object_1047.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1047.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1048"
                      geometry={gltf.nodes.Object_1048.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1048.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1049"
                      geometry={gltf.nodes.Object_1049.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1049.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1051"
                      geometry={gltf.nodes.Object_1051.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1051.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1052"
                      geometry={gltf.nodes.Object_1052.geometry}
                      material={gltf.materials.Clothes_B}
                      skeleton={gltf.nodes.Object_1052.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1053"
                      geometry={gltf.nodes.Object_1053.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1053.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1055"
                      geometry={gltf.nodes.Object_1055.geometry}
                      material={gltf.materials.Clothes_F}
                      skeleton={gltf.nodes.Object_1055.skeleton}
                    />
                    <T.SkinnedMesh
                      name="Object_1056"
                      geometry={gltf.nodes.Object_1056.geometry}
                      material={gltf.materials.Clothes_OutLine}
                      skeleton={gltf.nodes.Object_1056.skeleton}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="cs_grp">
                  <T.Group
                    name="cs_solid_triangle"
                    position={[-0.28, -0.05, -0.47]}
                    rotation={[Math.PI / 2, -1.57, 0]}
                    scale={0.22}
                  />
                  <T.Group name="cs_eyelid2" position={[-1.79, 0.17, -0.03]} scale={0.1} />
                  <T.Group
                    name="cs_jaw_square"
                    position={[2.91, -0.04, 0.46]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.28}
                  />
                  <T.Group
                    name="cs_half_circle"
                    position={[0.03, -0.05, -0.09]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.07}
                  />
                  <T.Group
                    name="cs_shoulderr"
                    position={[-0.71, -0.05, 0.67]}
                    rotation={[0, 0, Math.PI / 2]}
                    scale={0.08}
                  />
                  <T.Group
                    name="cs_shoulderl"
                    position={[-0.53, -0.05, 0.67]}
                    rotation={[0, 0, Math.PI / 2]}
                    scale={0.08}
                  />
                  <T.Group
                    name="cs_square"
                    position={[-5.74, -0.05, 0.82]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <T.Group name="cs_base_finger_end" position={[-2.89, -0.05, -0.16]} scale={0.1} />
                  <T.Group name="cs_base_finger" position={[-2.67, -0.05, -0.16]} scale={0.1} />
                  <T.Group
                    name="cs_circle_head"
                    position={[-5.03, -0.38, 0.81]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.07}
                  />
                  <T.Group
                    name="cs_semi_sphere_inv"
                    position={[-0.61, -0.05, 0.47]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.08}
                  />
                  <T.Group
                    name="cs_semi_sphere"
                    position={[-0.65, -0.05, 0.47]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.08}
                  />
                  <T.Group name="cs_fist" position={[7.97, 0, 0]} />
                  <T.Group
                    name="cs_ctrl_ik_solid_blue"
                    position={[5.16, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_ctrl_ik_solid_red"
                    position={[4.96, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.05}
                  />
                  <T.Group name="cs_c_eye_offset" position={[-1.62, -0.05, 0.17]} scale={0.1} />
                  <T.Group
                    name="cs_solid_pupil_blue"
                    position={[4.72, -0.05, -0.51]}
                    rotation={[0, 0, Math.PI]}
                    scale={0.21}
                  />
                  <T.Group
                    name="cs_solid_pupil_red"
                    position={[4.48, -0.05, -0.51]}
                    rotation={[0, 0, Math.PI]}
                    scale={0.22}
                  />
                  <T.Group
                    name="cs_solid_eye_red"
                    position={[3.92, -0.05, -0.51]}
                    rotation={[0, 0, Math.PI]}
                    scale={0.22}
                  />
                  <T.Group
                    name="cs_solid_eye_blue"
                    position={[4.16, -0.05, -0.51]}
                    rotation={[0, 0, Math.PI]}
                    scale={0.21}
                  />
                  <T.Group name="cs_user_c_thigh_fkr" position={[4.96, -0.07, -0.51]} />
                  <T.Group
                    name="cs_user_c_thigh_fkl"
                    position={[0.13, 0, 0.77]}
                    rotation={[-1.63, 0.01, -0.17]}
                    scale={0.41}
                  />
                  <T.Group name="cs_user_c_leg_fkr" position={[2.48, 0.05, 0.48]} />
                  <T.Group
                    name="cs_user_c_leg_fkl"
                    position={[0.17, -0.02, 0.53]}
                    rotation={[-0.88, 1.32, -0.64]}
                    scale={0.47}
                  />
                  <T.Group
                    name="cs_spine"
                    position={[0, -0.01, 1.07]}
                    rotation={[Math.PI / 2, -0.01, 0]}
                    scale={0.05}
                  />
                  <T.Group name="cs_hand" position={[2.48, 0.05, 0.48]} scale={0.1} />
                  <T.Group
                    name="cs_cube_03"
                    position={[-4.47, -0.38, 0.67]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.07}
                  />
                  <T.Group
                    name="cs_box_head"
                    position={[-3.9, -0.38, 0.81]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.07}
                  />
                  <T.Group
                    name="cs_cube_02"
                    position={[-3.44, -0.38, 0.87]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.07}
                  />
                  <T.Group name="cs_box" position={[-2.35, -0.05, -0.16]} scale={0.7} />
                  <T.Group name="cs_foot_roll" position={[-1.41, -0.05, -0.16]} scale={0.1} />
                  <T.Group name="cs_footl" position={[1.97, -0.05, 0.47]} scale={0.1} />
                  <T.Group name="cs_jaw" position={[2.45, -0.04, 0.46]} rotation={[0, 0, -Math.PI / 2]} scale={0.28} />
                  <T.Group name="cs_cube" position={[-2.8, -0.51, 0.86]} rotation={[Math.PI / 2, 0, 0]} scale={0.19} />
                  <T.Group name="cs_cheek_inflate" position={[0.53, -0.05, 0.12]} scale={0.1} />
                  <T.Group name="cs_wire_eyebrow" position={[3.57, -0.05, -0.46]} scale={0.25} />
                  <T.Group name="cs_solid_eyebrow_red" position={[3.08, -0.05, -0.46]} scale={0.25} />
                  <T.Group name="cs_solid_eyebrow_blue" position={[2.68, -0.05, -0.46]} scale={0.25} />
                  <T.Group name="cs_footr" position={[2.07, -0.05, 0.47]} scale={0.1} />
                  <T.Group name="cs_c_eyelid_micro" position={[-1.96, -0.05, 0.17]} scale={0.1} />
                  <T.Group name="cs_arrow_03" position={[1.23, -0.04, 0.04]} scale={0.28} />
                  <T.Group name="cs_pos" position={[-2.07, -0.05, 0.82]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
                  <T.Group name="cs_curve" position={[0.42, -0.05, 0.52]} scale={0.1} />
                  <T.Group name="cs_arrow_cross" position={[2.08, -0.04, 0.04]} scale={0.28} />
                  <T.Group name="cs_plane_5" position={[0.8, -0.05, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.05} />
                  <T.Group name="cs_fk" position={[-1.6, -0.05, 0.82]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
                  <T.Group name="cs_foot_fk" position={[-0.08, -0.05, 0.29]} scale={0.1} />
                  <T.Group name="cs_eyelid" position={[-1.79, -0.05, 0.07]} scale={0.1} />
                  <T.Group name="cs_c_eye" position={[-1.78, -0.05, 0.17]} scale={0.1} />
                  <T.Group name="cs_arrow" position={[1.03, -0.04, 0.04]} scale={0.28} />
                  <T.Group name="cs_arrow_02" position={[1.33, -0.04, 0.04]} scale={0.28} />
                  <T.Group
                    name="cs_circle_ik"
                    position={[-0.27, -0.05, -0.11]}
                    rotation={[Math.PI / 2, -1.57, 0]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_plane_4_fill"
                    position={[1.34, -0.05, 0.51]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <T.Group name="cs_torus_04_rot2" position={[-0.69, -0.05, -0.16]} scale={0.1} />
                  <T.Group name="cs_torus_04_rot" position={[-0.77, -0.05, -0.15]} scale={0.1} />
                  <T.Group name="cs_torus_05" position={[-0.94, -0.05, -0.16]} scale={0.1} />
                  <T.Group name="cs_triangle_02" position={[0.21, -0.05, 0.95]} rotation={[0, 0, 1.74]} scale={0.17} />
                  <T.Group
                    name="cs_triangle"
                    position={[-0.17, -0.05, 0.94]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                    scale={0.22}
                  />
                  <T.Group name="cs_plane_4" position={[0.85, -0.05, 0.5]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
                  <T.Group name="cs_circle_squashed" position={[0.53, -0.05, -0.06]} scale={0.1} />
                  <T.Group name="cs_yeux" position={[-1.04, -0.05, 0.46]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
                  <T.Group name="cs_plane_3" position={[0.64, -0.05, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.05} />
                  <T.Group
                    name="cs_plane_2"
                    position={[-1.06, -0.05, 0.82]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_circle_01"
                    position={[0.03, -0.05, -0.09]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_circle_02"
                    position={[0.33, -0.05, -0.08]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group name="cs_plane_1" position={[0.42, -0.05, 0.29]} scale={0.1} />
                  <T.Group name="cs_torus_04" position={[-1.26, -0.05, -0.16]} scale={0.1} />
                  <T.Group name="cs_torus_02" position={[-0.84, -0.05, 0.16]} scale={0.1} />
                  <T.Group name="cs_torus_03" position={[-0.26, -0.05, 0.16]} scale={0.1} />
                  <T.Group name="cs_torus_01" position={[-1.25, -0.05, 0.17]} scale={0.1} />
                  <T.Group
                    name="cs_sphere"
                    position={[-0.85, -0.05, 0.47]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.08}
                  />
                  <T.Group name="cs_sphere_dir2" position={[-0.75, -0.05, 0.47]} scale={0.09} />
                  <T.Group name="cs_sphere_dir1" position={[-0.55, -0.05, 0.48]} scale={0.08} />
                  <T.Group name="cs_arrow_twist" position={[5.25, -0.05, 0.31]} />
                  <T.Group
                    name="cs_arrow_cross_solid"
                    position={[-1.2, -0.04, -1.33]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.08}
                  />
                  <T.Group
                    name="cs_pos_solid_eye_offset_blue"
                    position={[-2.58, -0.05, -1.29]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.25}
                  />
                  <T.Group
                    name="cs_pos_solid_eye_offset_red"
                    position={[-3.08, -0.05, -1.29]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.25}
                  />
                  <T.Group name="cs_solid_arrow_twist_blue" position={[2.27, -0.05, -0.46]} scale={0.25} />
                  <T.Group name="cs_solid_arrow_twist_red" position={[1.86, -0.05, -0.46]} scale={0.25} />
                  <T.Group
                    name="cs_solid_bar_01"
                    position={[-1.92, -0.05, -0.5]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_bar_blue"
                    position={[-6.03, -0.23, -0.42]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_bar_red"
                    position={[-4.87, -0.05, -0.5]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_circle_01"
                    position={[0.03, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_circle_02"
                    position={[0.52, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_circle_02_blue"
                    position={[0.88, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_circle_02_green"
                    position={[0.33, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_circle_02_red"
                    position={[0.7, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_circle_ik_blue"
                    position={[-4.07, -0.05, -0.48]}
                    rotation={[-Math.PI / 2, -1.57, 0]}
                    scale={0.13}
                  />
                  <T.Group
                    name="cs_solid_circle_ik_red"
                    position={[-3.23, -0.05, -0.48]}
                    rotation={[-Math.PI / 2, -1.57, 0]}
                    scale={0.13}
                  />
                  <T.Group name="cs_solid_circle_squashed_blue" position={[0.1, -0.6, -1.15]} scale={0.37} />
                  <T.Group name="cs_solid_circle_squashed_green" position={[-0.43, -0.6, -1.15]} scale={0.37} />
                  <T.Group name="cs_solid_circle_squashed_red" position={[0.65, -0.6, -1.15]} scale={0.37} />
                  <T.Group
                    name="cs_solid_fk_blue"
                    position={[-3.71, -0.05, -0.48]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={0.06}
                  />
                  <T.Group
                    name="cs_solid_fk_red"
                    position={[-2.87, -0.05, -0.48]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={0.06}
                  />
                  <T.Group
                    name="cs_solid_plane_2"
                    position={[-1.18, -0.05, -0.5]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_solid_plane_2_blue"
                    position={[-0.63, -0.05, -0.5]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_solid_plane_2_red"
                    position={[-0.89, -0.05, -0.5]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_solid_plane_3"
                    position={[0.98, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_solid_plane_3_blue"
                    position={[1.36, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_solid_plane_3_red"
                    position={[1.15, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_solid_plane_5_blue"
                    position={[1.61, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_solid_plane_5_red"
                    position={[1.52, -0.05, -0.51]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.05}
                  />
                  <T.Group name="cs_solid_torus_04_blue" position={[-2.53, -0.05, -0.48]} scale={0.1} />
                  <T.Group name="cs_solid_torus_04_red" position={[-2.61, -0.05, -0.48]} scale={0.1} />
                  <T.Group name="cs_solid_torus_blue" position={[-3.84, -0.05, -1.28]} scale={0.1} />
                  <T.Group name="cs_solid_torus_green" position={[-4.09, -0.05, -1.28]} scale={0.1} />
                  <T.Group name="cs_solid_torus_red" position={[-3.6, -0.05, -1.28]} scale={0.1} />
                  <T.Group
                    name="cs_pos_solid"
                    position={[-2.07, -0.05, -1.29]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_eye_aim_blue"
                    position={[-1.96, -0.05, -0.04]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_eye_aim_global"
                    position={[-1.84, -0.05, -0.09]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_solid_eye_aim_red"
                    position={[-2.08, -0.05, -0.04]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_eye_aim"
                    position={[-1.55, -0.05, -0.09]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_eye_aim_global"
                    position={[-1.71, -0.05, -0.09]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.1}
                  />
                  <T.Group
                    name="cs_user_c_skull_01x"
                    position={[0, -0.02, 1.57]}
                    rotation={[-Math.PI / 2, 1.57, 0]}
                    scale={0.06}
                  />
                  <T.Group
                    name="cs_user_c_shoulderl"
                    position={[0.08, -0.06, 1.4]}
                    rotation={[-Math.PI, 0, -1.54]}
                    scale={0.08}
                  />
                  <T.Group name="cs_user_c_shoulderr" position={[-1.73, 0.12, 0.13]} />
                  <T.Group
                    name="cs_user_c_skull_02x"
                    position={[0, -0.02, 1.57]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.05}
                  />
                  <T.Group
                    name="cs_user_c_skull_03x"
                    position={[0, -0.02, 1.67]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.06}
                  />
                  <T.Group name="cs_twist_shape" position={[-0.48, -0.05, 0.16]} scale={0.1} />
                  <T.Group name="cs_torus_tip_01" position={[-0.99, 0, 0]} />
                  <T.Group name="cs_wavy_circle" position={[6.98, 0, 0]} />
                  <T.Group name="cs_arrow_x_up" position={[1.03, -0.14, 0.04]} scale={0.28} />
                  <T.Group name="cs_arrow_x_down" position={[1.03, -0.24, 0.04]} scale={0.28} />
                  <T.Group name="cs_c_foot_ik_offset" rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.11} />
                  <T.Group name="cs_fly" position={[3.68, -0.04, 0.04]} scale={0.28} />
                  <T.Group name="cs_cube_solid" position={[-3.95, 0, 0]} />
                  <T.Group name="cs_cube_solid_offset" position={[-4.35, 0, 0]} />
                  <T.Group
                    name="cs_sphere_offset"
                    position={[-0.85, -0.05, 0.56]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.08}
                  />
                  <T.Group name="cs_sphere_solid_offset" position={[-5.18, 0, 0]} />
                  <T.Group name="cs_box_offset" position={[-5.75, 0, 0]} />
                  <T.Group name="cs_sphere_solid" position={[-4.75, 0, 0]} />
                  <T.Group
                    name="cs_user_c_arm_fkl"
                    position={[0.24, 0.03, 1.29]}
                    rotation={[3.11, -0.37, -1.68]}
                    scale={0.23}
                  />
                  <T.Group name="cs_user_c_arm_fkr" position={[0.13, 0.01, 1.34]} />
                  <T.Group name="cs_user_c_arm_ikr" position={[0.13, 0.01, 1.34]} />
                </T.Group>
              </T.Group>
              <T.Group name="Torso_Ear" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Torso_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Torso_Eyelash" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Torso_Eye_R" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair003" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair004" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair005" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair007" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair008" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair010" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair009" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair006" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair011" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair012" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair013" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair030" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair031" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair032" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair033" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair034" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair035" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair036" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair037" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair040" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair041" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair042" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair043" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair044" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair045" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair_BandeauA002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair_BandeauB002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair_BandeauC002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair038" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair039" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair014" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair015" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair016" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair017" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair018" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair019" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair020" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair021" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair024" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair025" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair026" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair027" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair028" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair029" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair_BandeauA001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair_BandeauB001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair_BandeauC001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair022" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair023" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Hair046" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Underwear_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Shoes_L_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Socks_L_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Shoes_R_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Socks_R_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Necktie001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_PleatedSuspenders" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Necktie002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Necktie003" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Necktie004" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_PleatedSkirt_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_PleatedButton" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_OvercoatButton" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Shirt_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_Overcoat_SS" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="Clothes_OvercoatPocket" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
